name: Trigger auto deployment for testedessa12

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/testedessa12-AutoDeployTrigger-1fc3e252-a51b-403f-915f-89d1e7a9eccf.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TESTEDESSA12_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTEDESSA12_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTEDESSA12_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: azacrxq745qawrjl4s.azurecr.io
          registryUsername: ${{ secrets.TESTEDESSA12_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTEDESSA12_REGISTRY_PASSWORD }}
          containerAppName: testedessa12
          resourceGroup: Default-ActivityLogAlerts
          imageToBuild: azacrxq745qawrjl4s.azurecr.io/testedessa12:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


